import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Storeth | Databases",
    description: "Generated by create next app"
};

export default function DatabasesLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return <>{children}</>;
}
