import "./globals.css";
import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/toaster";
import { headers } from "next/headers";
import { Inter as FontSans } from "next/font/google";
import { cookieToInitialState } from "wagmi";
import { config } from "@/config";
import { ContextProvider } from "@/context";
import { cn } from "@/lib/utils";

export const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans"
});

export const metadata: Metadata = {
    title: "Storeth | Home",
    description: "Generated by create next app"
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    const initialState = cookieToInitialState(config, headers().get("cookie"));
    return (
        <html lang="en">
            <body
                className={cn(
                    "bg-background min-h-screen font-sans antialiased",
                    fontSans.variable
                )}
            >
                <ContextProvider initialState={initialState}>
                    <div className="flex min-h-screen flex-col bg-white px-8 dark:bg-[#111110]">
                        <Navbar />
                        <main className="mx-auto flex w-full max-w-4xl">{children}</main>
                        <Toaster />
                        <Footer />
                    </div>
                </ContextProvider>
            </body>
        </html>
    );
}
